<a href="https://colab.research.google.com/github/24221395-glitch/data_Science_W1/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Cell 1: imports and shape variables
import numpy as np

# You can change n, p, m to any integers
n = 2
p = 3
m = 4


In [2]:
# 1) 2 x 2 array (example)
arr_2x2 = np.array([[1, 2],
                    [3, 4]])
print("2x2 array:\n", arr_2x2)


2x2 array:
 [[1 2]
 [3 4]]


In [3]:
# 2) random 3 x 4 array (values in [0,1))
rand_3x4 = np.random.random((3, 4))
print("Random 3x4 array:\n", rand_3x4)


Random 3x4 array:
 [[0.46858504 0.64905343 0.15650661 0.1723565 ]
 [0.41016679 0.89206113 0.10453455 0.61356635]
 [0.37398958 0.90965611 0.91338715 0.70350244]]


In [4]:
# 3) ones and zeros
ones_3x2 = np.ones((3, 2))
zeros_2x5 = np.zeros((2, 5))
print("Ones 3x2:\n", ones_3x2)
print("Zeros 2x5:\n", zeros_2x5)


Ones 3x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Zeros 2x5:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
# 4) random 6x3 and transpose -> becomes 3x6
rand_6x3 = np.random.random((6, 3))
rand_6x3_T = rand_6x3.T
print("Random 6x3:\n", rand_6x3)
print("Transposed (3x6):\n", rand_6x3_T)


Random 6x3:
 [[0.24957326 0.42708158 0.71235859]
 [0.33906736 0.41061104 0.24799292]
 [0.92226974 0.14429394 0.81278953]
 [0.9990109  0.73121628 0.06841155]
 [0.79446143 0.58996592 0.03208313]
 [0.54417531 0.30205822 0.6876747 ]]
Transposed (3x6):
 [[0.24957326 0.33906736 0.92226974 0.9990109  0.79446143 0.54417531]
 [0.42708158 0.41061104 0.14429394 0.73121628 0.58996592 0.30205822]
 [0.71235859 0.24799292 0.81278953 0.06841155 0.03208313 0.6876747 ]]


In [6]:
# 5) dot product of (n x p) and (p x m) -> result (n x m)
A = np.random.random((n, p))
B = np.random.random((p, m))
C = A.dot(B)   # or np.dot(A, B)
print(f"A shape: {A.shape}, B shape: {B.shape}, Result C shape: {C.shape}")
print("A:\n", A)
print("B:\n", B)
print("A dot B = C:\n", C)


A shape: (2, 3), B shape: (3, 4), Result C shape: (2, 4)
A:
 [[0.46262617 0.74336282 0.20280599]
 [0.22183058 0.25029976 0.02585332]]
B:
 [[0.26279197 0.6578781  0.16695216 0.26717399]
 [0.27533683 0.7330241  0.0184275  0.3992826 ]
 [0.41637195 0.3062849  0.93459567 0.66446528]]
A dot B = C:
 [[0.41069233 0.9113709  0.28047636 0.55517106]
 [0.13797663 0.33733172 0.06580989 0.17638633]]


In [7]:
# integer random example
A_int = np.random.randint(0, 10, (n, p))
B_int = np.random.randint(0, 10, (p, m))
C_int = A_int @ B_int
print("Integer A:\n", A_int)
print("Integer B:\n", B_int)
print("Integer A @ B:\n", C_int)


Integer A:
 [[7 4 4]
 [6 3 2]]
Integer B:
 [[8 7 9 5]
 [4 7 4 9]
 [0 7 6 0]]
Integer A @ B:
 [[ 72 105 103  71]
 [ 60  77  78  57]]
